import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import '@/styles/globals.css'
import { AppSidebar } from '@/components/app-sidebar'
import { SiteHeader } from '@/components/site-header'
import { SidebarProvider, SidebarInset } from '@/components/sidebar'
import { Toaster } from '@/components/sonner'
import { TRPCProvider } from '@/trpc-server/client-provider'

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
})

export const metadata: Metadata = {
   title: 'QueueDash',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body className={`${geistSans.variable} antialiased`}>
            <TRPCProvider>
               <Toaster />
               <SidebarProvider
                  style={
                     {
                        '--sidebar-width': 'calc(var(--spacing) * 72)',
                        '--header-height': 'calc(var(--spacing) * 12)',
                     } as React.CSSProperties
                  }
               >
                  <AppSidebar variant="inset" />
                  <SidebarInset>
                     <SiteHeader />
                     <div className="flex flex-1 flex-col">{children}</div>
                  </SidebarInset>
               </SidebarProvider>
            </TRPCProvider>
         </body>
      </html>
   )
}
